In [1]:
import pandas as pd
import numpy as np 
import requests

In [2]:
df= pd.read_csv(r"C:\Users\himan\Education1\Projects\NLP\data\IMDB Dataset.csv", )
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df['review']= df['review'].str.lower()

In [4]:
df.head(10)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive
5  probably my all-time favorite movie, a story o...  positive
6  i sure would like to see a resurrection of a u...  positive
7  this show was an amazing, fresh & innovative i...  negative
8  encouraged by the positive comments about this...  negative
9  if you like original gut wrenching laughter yo...  positive

In [5]:
import re
def remove_html_tags (text):
    pattern= re.compile('<.*?>')
    return pattern.sub(r'', text)

In [6]:
df["review"]= df["review"].apply(remove_html_tags)

In [7]:
df["review"][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [8]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [9]:
exclude= string.punctuation

In [10]:
def remove_panc(text):
    for char in exclude:
        text=text.replace(char,'') 
    return text

In [11]:
df["review"]= df["review"].apply(remove_panc)

In [12]:
df["review"][3]

'basically theres a family where a little boy jake thinks theres a zombie in his closet  his parents are fighting all the timethis movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombieok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing  arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots3 out of 10 just for the well playing parents  descent dialogs as for the shots with jake just ignore them'

In [13]:
from nltk.corpus import stopwords

In [14]:
a= stopwords.words('english')

In [15]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\himan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
def remove_stopwords(text):
    new_text=[]
    for word in text.split():
        if word in a:
            new_text.append('')
        else:
            new_text.append(word)
    x= new_text[:]
    new_text.clear()
    return " ".join(x)

In [17]:
df["review"]= df["review"].apply(remove_stopwords)

In [18]:
df.head()

                                              review sentiment
0  one    reviewers  mentioned   watching  1 oz e...  positive
1   wonderful little production  filming techniqu...  positive
2   thought    wonderful way  spend time    hot s...  positive
3  basically theres  family   little boy jake thi...  negative
4  petter matteis love   time  money   visually s...  positive

In [19]:

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [20]:

remove_emoji('Loved the movie. It was 😍😊')

'Loved the movie. It was '

In [21]:
import emoji

In [22]:
print(emoji.demojize('Lmao 😂😂'))

Lmao :face_with_tears_of_joy::face_with_tears_of_joy:

In [23]:
df['review'][3].split()

['basically',
 'theres',
 'family',
 'little',
 'boy',
 'jake',
 'thinks',
 'theres',
 'zombie',
 'closet',
 'parents',
 'fighting',
 'timethis',
 'movie',
 'slower',
 'soap',
 'opera',
 'suddenly',
 'jake',
 'decides',
 'become',
 'rambo',
 'kill',
 'zombieok',
 'first',
 'youre',
 'going',
 'make',
 'film',
 'must',
 'decide',
 'thriller',
 'drama',
 'drama',
 'movie',
 'watchable',
 'parents',
 'divorcing',
 'arguing',
 'like',
 'real',
 'life',
 'jake',
 'closet',
 'totally',
 'ruins',
 'film',
 'expected',
 'see',
 'boogeyman',
 'similar',
 'movie',
 'instead',
 'watched',
 'drama',
 'meaningless',
 'thriller',
 'spots3',
 '10',
 'well',
 'playing',
 'parents',
 'descent',
 'dialogs',
 'shots',
 'jake',
 'ignore']

In [24]:
df['review'][3].split(".")

['basically theres  family   little boy jake thinks theres  zombie   closet  parents  fighting   timethis movie  slower   soap opera  suddenly jake decides  become rambo  kill  zombieok first    youre going  make  film  must decide    thriller   drama   drama  movie  watchable parents  divorcing arguing like  real life     jake   closet  totally ruins   film  expected  see  boogeyman similar movie  instead  watched  drama   meaningless thriller spots3   10    well playing parents descent dialogs    shots  jake  ignore ']

In [25]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [26]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\himan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\himan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [27]:
word_tokenize(df['review'].iloc[0])

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'youll',
 'hooked',
 'right',
 'exactly',
 'happened',
 'methe',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'wordit',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'manyaryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'awayi',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'wouldnt',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceoz',
 'doesnt',
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'couldnt',
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'sold',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewingthats',
 'get',
 'touch',
 'darker',
 'side']

In [28]:


# Word-level tokenization
print(df['review'].apply(word_tokenize))


print("# Sentence-level tokenization")
df['review'].apply(sent_tokenize)

0        [one, reviewers, mentioned, watching, 1, oz, e...
1        [wonderful, little, production, filming, techn...
2        [thought, wonderful, way, spend, time, hot, su...
3        [basically, theres, family, little, boy, jake,...
4        [petter, matteis, love, time, money, visually,...
                               ...
49995    [thought, movie, right, good, job, wasnt, crea...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [catholic, taught, parochial, elementary, scho...
49998    [im, going, disagree, previous, comment, side,...
49999    [one, expects, star, trek, movies, high, art, ...
Name: review, Length: 50000, dtype: object
# Sentence-level tokenization

0        [one    reviewers  mentioned   watching  1 oz ...
1        [ wonderful little production  filming techniq...
2        [ thought    wonderful way  spend time    hot ...
3        [basically theres  family   little boy jake th...
4        [petter matteis love   time  money   visually ...
                               ...
49995    [ thought  movie    right good job  wasnt  cre...
49996    [bad plot bad dialogue bad acting idiotic dire...
49997    [   catholic taught  parochial elementary scho...
49998    [im going    disagree   previous comment  side...
49999    [ one expects  star trek movies   high art   f...
Name: review, Length: 50000, dtype: object

In [30]:
df

                                                  review sentiment
0      one    reviewers  mentioned   watching  1 oz e...  positive
1       wonderful little production  filming techniqu...  positive
2       thought    wonderful way  spend time    hot s...  positive
3      basically theres  family   little boy jake thi...  negative
4      petter matteis love   time  money   visually s...  positive
...                                                  ...       ...
49995   thought  movie    right good job  wasnt  crea...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997     catholic taught  parochial elementary schoo...  negative
49998  im going    disagree   previous comment  side ...  negative
49999   one expects  star trek movies   high art   fa...  negative

[50000 rows x 2 columns]

In [32]:
X= df.iloc[:,0:1]
y= df['sentiment']

In [33]:
X

                                                  review
0      one    reviewers  mentioned   watching  1 oz e...
1       wonderful little production  filming techniqu...
2       thought    wonderful way  spend time    hot s...
3      basically theres  family   little boy jake thi...
4      petter matteis love   time  money   visually s...
...                                                  ...
49995   thought  movie    right good job  wasnt  crea...
49996  bad plot bad dialogue bad acting idiotic direc...
49997     catholic taught  parochial elementary schoo...
49998  im going    disagree   previous comment  side ...
49999   one expects  star trek movies   high art   fa...

[50000 rows x 1 columns]

In [34]:
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 50000, dtype: str

# Text Classification using BoW

In [35]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder() 
y= le.fit_transform(y)

In [38]:
y[0:5]

array([1, 1, 1, 0, 1])

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=1)

In [43]:
X_train.shape

(40000, 1)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [61]:
cv= CountVectorizer(
    min_df=2,
    max_df=0.98)

In [62]:
X_train_bow = cv.fit_transform(X_train['review'])
X_test_bow = cv.transform(X_test['review'])

In [64]:
X_train_bow.shape

(40000, 70403)

# Using MultiNomialNB

In [66]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

mnb.fit(X_train_bow,y_train)

MultinomialNB()

In [69]:
y_pred = mnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.8638

In [70]:
confusion_matrix(y_test,y_pred)

array([[4459,  585],
       [ 777, 4179]])

# Using randomForestClassifer

In [71]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8586

# Tf-idf

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [77]:
X_train_tfidf = tfidf.fit_transform(X_train['review'])
X_test_tfidf = tfidf.transform(X_test['review'])

In [78]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8526